# Generated by Django 4.2.7 on 2023-12-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repybo', '0004_answer_modify_date_question_modify_date'),
        ('repybo', '0004_rename_created_date_answer_create_date_and_more'),
    ]

    operations = [
    ]
