# Generated by Django 4.2.7 on 2023-12-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repybo', '0006_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
